// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: costs.sql

package db

import (
	"context"
	"database/sql"
)

const createCostRecord = `-- name: CreateCostRecord :execresult
INSERT INTO cost_records (id, session_id, project, provider, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, total_cost)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateCostRecordParams struct {
	ID               string          `json:"id"`
	SessionID        string          `json:"session_id"`
	Project          string          `json:"project"`
	Provider         string          `json:"provider"`
	Model            string          `json:"model"`
	InputTokens      sql.NullInt64   `json:"input_tokens"`
	OutputTokens     sql.NullInt64   `json:"output_tokens"`
	CacheReadTokens  sql.NullInt64   `json:"cache_read_tokens"`
	CacheWriteTokens sql.NullInt64   `json:"cache_write_tokens"`
	TotalCost        sql.NullFloat64 `json:"total_cost"`
}

func (q *Queries) CreateCostRecord(ctx context.Context, arg CreateCostRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCostRecord,
		arg.ID,
		arg.SessionID,
		arg.Project,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.TotalCost,
	)
}

const getBudget = `-- name: GetBudget :one
SELECT project, daily_limit, weekly_limit, monthly_limit, warning_pct, updated_at FROM budgets WHERE project = ?
`

func (q *Queries) GetBudget(ctx context.Context, project string) (Budget, error) {
	row := q.db.QueryRowContext(ctx, getBudget, project)
	var i Budget
	err := row.Scan(
		&i.Project,
		&i.DailyLimit,
		&i.WeeklyLimit,
		&i.MonthlyLimit,
		&i.WarningPct,
		&i.UpdatedAt,
	)
	return i, err
}

const getCostByProject = `-- name: GetCostByProject :one
SELECT CAST(COALESCE(SUM(total_cost), 0) AS REAL) AS total_cost, CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens, CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens
FROM cost_records WHERE project = ?
`

type GetCostByProjectRow struct {
	TotalCost    float64 `json:"total_cost"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
}

func (q *Queries) GetCostByProject(ctx context.Context, project string) (GetCostByProjectRow, error) {
	row := q.db.QueryRowContext(ctx, getCostByProject, project)
	var i GetCostByProjectRow
	err := row.Scan(&i.TotalCost, &i.InputTokens, &i.OutputTokens)
	return i, err
}

const getCostByProjectMonth = `-- name: GetCostByProjectMonth :one
SELECT CAST(COALESCE(SUM(total_cost), 0) AS REAL) AS total_cost, CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens, CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens
FROM cost_records WHERE project = ? AND recorded_at >= date('now', '-30 days')
`

type GetCostByProjectMonthRow struct {
	TotalCost    float64 `json:"total_cost"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
}

func (q *Queries) GetCostByProjectMonth(ctx context.Context, project string) (GetCostByProjectMonthRow, error) {
	row := q.db.QueryRowContext(ctx, getCostByProjectMonth, project)
	var i GetCostByProjectMonthRow
	err := row.Scan(&i.TotalCost, &i.InputTokens, &i.OutputTokens)
	return i, err
}

const getCostByProjectToday = `-- name: GetCostByProjectToday :one
SELECT CAST(COALESCE(SUM(total_cost), 0) AS REAL) AS total_cost, CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens, CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens
FROM cost_records WHERE project = ? AND date(recorded_at) = date('now')
`

type GetCostByProjectTodayRow struct {
	TotalCost    float64 `json:"total_cost"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
}

func (q *Queries) GetCostByProjectToday(ctx context.Context, project string) (GetCostByProjectTodayRow, error) {
	row := q.db.QueryRowContext(ctx, getCostByProjectToday, project)
	var i GetCostByProjectTodayRow
	err := row.Scan(&i.TotalCost, &i.InputTokens, &i.OutputTokens)
	return i, err
}

const getCostByProjectWeek = `-- name: GetCostByProjectWeek :one
SELECT CAST(COALESCE(SUM(total_cost), 0) AS REAL) AS total_cost, CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens, CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens
FROM cost_records WHERE project = ? AND recorded_at >= date('now', '-7 days')
`

type GetCostByProjectWeekRow struct {
	TotalCost    float64 `json:"total_cost"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
}

func (q *Queries) GetCostByProjectWeek(ctx context.Context, project string) (GetCostByProjectWeekRow, error) {
	row := q.db.QueryRowContext(ctx, getCostByProjectWeek, project)
	var i GetCostByProjectWeekRow
	err := row.Scan(&i.TotalCost, &i.InputTokens, &i.OutputTokens)
	return i, err
}

const getCostBySession = `-- name: GetCostBySession :one
SELECT CAST(COALESCE(SUM(total_cost), 0) AS REAL) AS total_cost, CAST(COALESCE(SUM(input_tokens), 0) AS INTEGER) AS input_tokens, CAST(COALESCE(SUM(output_tokens), 0) AS INTEGER) AS output_tokens
FROM cost_records WHERE session_id = ?
`

type GetCostBySessionRow struct {
	TotalCost    float64 `json:"total_cost"`
	InputTokens  int64   `json:"input_tokens"`
	OutputTokens int64   `json:"output_tokens"`
}

func (q *Queries) GetCostBySession(ctx context.Context, sessionID string) (GetCostBySessionRow, error) {
	row := q.db.QueryRowContext(ctx, getCostBySession, sessionID)
	var i GetCostBySessionRow
	err := row.Scan(&i.TotalCost, &i.InputTokens, &i.OutputTokens)
	return i, err
}

const listCostRecords = `-- name: ListCostRecords :many
SELECT id, session_id, project, provider, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, total_cost, recorded_at FROM cost_records
WHERE project = ?
ORDER BY recorded_at DESC
LIMIT ?
`

type ListCostRecordsParams struct {
	Project string `json:"project"`
	Limit   int64  `json:"limit"`
}

func (q *Queries) ListCostRecords(ctx context.Context, arg ListCostRecordsParams) ([]CostRecord, error) {
	rows, err := q.db.QueryContext(ctx, listCostRecords, arg.Project, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CostRecord{}
	for rows.Next() {
		var i CostRecord
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Project,
			&i.Provider,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.TotalCost,
			&i.RecordedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCostRecordsByDate = `-- name: ListCostRecordsByDate :many
SELECT date(recorded_at) as day, SUM(total_cost) as total, SUM(input_tokens) as input, SUM(output_tokens) as output
FROM cost_records
WHERE project = ? AND recorded_at >= date('now', '-30 days')
GROUP BY day
ORDER BY day DESC
`

type ListCostRecordsByDateRow struct {
	Day    interface{}     `json:"day"`
	Total  sql.NullFloat64 `json:"total"`
	Input  sql.NullFloat64 `json:"input"`
	Output sql.NullFloat64 `json:"output"`
}

func (q *Queries) ListCostRecordsByDate(ctx context.Context, project string) ([]ListCostRecordsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, listCostRecordsByDate, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCostRecordsByDateRow{}
	for rows.Next() {
		var i ListCostRecordsByDateRow
		if err := rows.Scan(
			&i.Day,
			&i.Total,
			&i.Input,
			&i.Output,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBudget = `-- name: UpsertBudget :exec
INSERT INTO budgets (project, daily_limit, weekly_limit, monthly_limit, warning_pct)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(project) DO UPDATE SET
    daily_limit = excluded.daily_limit,
    weekly_limit = excluded.weekly_limit,
    monthly_limit = excluded.monthly_limit,
    warning_pct = excluded.warning_pct,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertBudgetParams struct {
	Project      string          `json:"project"`
	DailyLimit   sql.NullFloat64 `json:"daily_limit"`
	WeeklyLimit  sql.NullFloat64 `json:"weekly_limit"`
	MonthlyLimit sql.NullFloat64 `json:"monthly_limit"`
	WarningPct   float64         `json:"warning_pct"`
}

func (q *Queries) UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error {
	_, err := q.db.ExecContext(ctx, upsertBudget,
		arg.Project,
		arg.DailyLimit,
		arg.WeeklyLimit,
		arg.MonthlyLimit,
		arg.WarningPct,
	)
	return err
}
