// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: memories.sql

package db

import (
	"context"
	"database/sql"
)

const createMemory = `-- name: CreateMemory :execresult
INSERT INTO memories (id, project, type, key, value, source, confidence)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMemoryParams struct {
	ID         string  `json:"id"`
	Project    string  `json:"project"`
	Type       string  `json:"type"`
	Key        string  `json:"key"`
	Value      string  `json:"value"`
	Source     string  `json:"source"`
	Confidence float64 `json:"confidence"`
}

func (q *Queries) CreateMemory(ctx context.Context, arg CreateMemoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMemory,
		arg.ID,
		arg.Project,
		arg.Type,
		arg.Key,
		arg.Value,
		arg.Source,
		arg.Confidence,
	)
}

const deleteMemory = `-- name: DeleteMemory :exec
DELETE FROM memories WHERE id = ?
`

func (q *Queries) DeleteMemory(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteMemory, id)
	return err
}

const getMemory = `-- name: GetMemory :one
SELECT id, project, type, "key", value, source, confidence, usage_count, last_used_at, created_at, updated_at FROM memories WHERE project = ? AND key = ?
`

type GetMemoryParams struct {
	Project string `json:"project"`
	Key     string `json:"key"`
}

func (q *Queries) GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error) {
	row := q.db.QueryRowContext(ctx, getMemory, arg.Project, arg.Key)
	var i Memory
	err := row.Scan(
		&i.ID,
		&i.Project,
		&i.Type,
		&i.Key,
		&i.Value,
		&i.Source,
		&i.Confidence,
		&i.UsageCount,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMemories = `-- name: ListMemories :many
SELECT id, project, type, "key", value, source, confidence, usage_count, last_used_at, created_at, updated_at FROM memories
WHERE project = ?
ORDER BY usage_count DESC, updated_at DESC
`

func (q *Queries) ListMemories(ctx context.Context, project string) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemories, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Type,
			&i.Key,
			&i.Value,
			&i.Source,
			&i.Confidence,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByType = `-- name: ListMemoriesByType :many
SELECT id, project, type, "key", value, source, confidence, usage_count, last_used_at, created_at, updated_at FROM memories
WHERE project = ? AND type = ?
ORDER BY usage_count DESC
`

type ListMemoriesByTypeParams struct {
	Project string `json:"project"`
	Type    string `json:"type"`
}

func (q *Queries) ListMemoriesByType(ctx context.Context, arg ListMemoriesByTypeParams) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, listMemoriesByType, arg.Project, arg.Type)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Type,
			&i.Key,
			&i.Value,
			&i.Source,
			&i.Confidence,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMemories = `-- name: SearchMemories :many
SELECT id, project, type, "key", value, source, confidence, usage_count, last_used_at, created_at, updated_at FROM memories
WHERE project = ? AND (key LIKE '%' || ? || '%' OR value LIKE '%' || ? || '%')
ORDER BY usage_count DESC
LIMIT ?
`

type SearchMemoriesParams struct {
	Project string         `json:"project"`
	Column2 sql.NullString `json:"column_2"`
	Column3 sql.NullString `json:"column_3"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]Memory, error) {
	rows, err := q.db.QueryContext(ctx, searchMemories,
		arg.Project,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Memory{}
	for rows.Next() {
		var i Memory
		if err := rows.Scan(
			&i.ID,
			&i.Project,
			&i.Type,
			&i.Key,
			&i.Value,
			&i.Source,
			&i.Confidence,
			&i.UsageCount,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMemory = `-- name: UpdateMemory :exec
UPDATE memories SET value = ?, confidence = ?, usage_count = usage_count + 1,
    last_used_at = strftime('%Y-%m-%dT%H:%M:%fZ','now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
WHERE id = ?
`

type UpdateMemoryParams struct {
	Value      string  `json:"value"`
	Confidence float64 `json:"confidence"`
	ID         string  `json:"id"`
}

func (q *Queries) UpdateMemory(ctx context.Context, arg UpdateMemoryParams) error {
	_, err := q.db.ExecContext(ctx, updateMemory, arg.Value, arg.Confidence, arg.ID)
	return err
}

const upsertMemory = `-- name: UpsertMemory :exec
INSERT INTO memories (id, project, type, key, value, source, confidence)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    value = excluded.value,
    confidence = excluded.confidence,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertMemoryParams struct {
	ID         string  `json:"id"`
	Project    string  `json:"project"`
	Type       string  `json:"type"`
	Key        string  `json:"key"`
	Value      string  `json:"value"`
	Source     string  `json:"source"`
	Confidence float64 `json:"confidence"`
}

func (q *Queries) UpsertMemory(ctx context.Context, arg UpsertMemoryParams) error {
	_, err := q.db.ExecContext(ctx, upsertMemory,
		arg.ID,
		arg.Project,
		arg.Type,
		arg.Key,
		arg.Value,
		arg.Source,
		arg.Confidence,
	)
	return err
}
