// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package db

import (
	"context"
	"database/sql"
)

const countMessagesBySession = `-- name: CountMessagesBySession :one
SELECT COUNT(*) FROM messages WHERE session_id = ?
`

func (q *Queries) CountMessagesBySession(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMessagesBySession, sessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createMessage = `-- name: CreateMessage :execresult
INSERT INTO messages (session_id, role, content, tool_calls, timestamp)
VALUES (?, ?, ?, ?, ?)
`

type CreateMessageParams struct {
	SessionID string         `json:"session_id"`
	Role      string         `json:"role"`
	Content   string         `json:"content"`
	ToolCalls sql.NullString `json:"tool_calls"`
	Timestamp string         `json:"timestamp"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMessage,
		arg.SessionID,
		arg.Role,
		arg.Content,
		arg.ToolCalls,
		arg.Timestamp,
	)
}

const deleteMessagesBySession = `-- name: DeleteMessagesBySession :exec
DELETE FROM messages WHERE session_id = ?
`

func (q *Queries) DeleteMessagesBySession(ctx context.Context, sessionID string) error {
	_, err := q.db.ExecContext(ctx, deleteMessagesBySession, sessionID)
	return err
}

const getMessage = `-- name: GetMessage :one
SELECT id, session_id, role, content, tool_calls, timestamp FROM messages WHERE id = ?
`

func (q *Queries) GetMessage(ctx context.Context, id int64) (Message, error) {
	row := q.db.QueryRowContext(ctx, getMessage, id)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Content,
		&i.ToolCalls,
		&i.Timestamp,
	)
	return i, err
}

const getMessagesBySession = `-- name: GetMessagesBySession :many
SELECT id, session_id, role, content, tool_calls, timestamp FROM messages
WHERE session_id = ?
ORDER BY timestamp ASC
`

func (q *Queries) GetMessagesBySession(ctx context.Context, sessionID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Content,
			&i.ToolCalls,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
