// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

type Budget struct {
	Project      string          `json:"project"`
	DailyLimit   sql.NullFloat64 `json:"daily_limit"`
	WeeklyLimit  sql.NullFloat64 `json:"weekly_limit"`
	MonthlyLimit sql.NullFloat64 `json:"monthly_limit"`
	WarningPct   float64         `json:"warning_pct"`
	UpdatedAt    string          `json:"updated_at"`
}

type CostRecord struct {
	ID               string          `json:"id"`
	SessionID        string          `json:"session_id"`
	Project          string          `json:"project"`
	Provider         string          `json:"provider"`
	Model            string          `json:"model"`
	InputTokens      sql.NullInt64   `json:"input_tokens"`
	OutputTokens     sql.NullInt64   `json:"output_tokens"`
	CacheReadTokens  sql.NullInt64   `json:"cache_read_tokens"`
	CacheWriteTokens sql.NullInt64   `json:"cache_write_tokens"`
	TotalCost        sql.NullFloat64 `json:"total_cost"`
	RecordedAt       string          `json:"recorded_at"`
}

type FileChange struct {
	ID             string         `json:"id"`
	SessionID      string         `json:"session_id"`
	FilePath       string         `json:"file_path"`
	Additions      sql.NullInt64  `json:"additions"`
	Deletions      sql.NullInt64  `json:"deletions"`
	Classification sql.NullString `json:"classification"`
	Accepted       sql.NullInt64  `json:"accepted"`
	CreatedAt      string         `json:"created_at"`
}

type MemoriesFt struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Memory struct {
	ID         string         `json:"id"`
	Project    string         `json:"project"`
	Type       string         `json:"type"`
	Key        string         `json:"key"`
	Value      string         `json:"value"`
	Source     string         `json:"source"`
	Confidence float64        `json:"confidence"`
	UsageCount int64          `json:"usage_count"`
	LastUsedAt sql.NullString `json:"last_used_at"`
	CreatedAt  string         `json:"created_at"`
	UpdatedAt  string         `json:"updated_at"`
}

type Message struct {
	ID        int64          `json:"id"`
	SessionID string         `json:"session_id"`
	Role      string         `json:"role"`
	Content   string         `json:"content"`
	ToolCalls sql.NullString `json:"tool_calls"`
	Timestamp string         `json:"timestamp"`
}

type Mistake struct {
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
	Type        string         `json:"type"`
	Description string         `json:"description"`
	Context     sql.NullString `json:"context"`
	Correction  sql.NullString `json:"correction"`
	FilePath    sql.NullString `json:"file_path"`
	CreatedAt   string         `json:"created_at"`
}

type ModelPerformance struct {
	ID             string  `json:"id"`
	Model          string  `json:"model"`
	TaskType       string  `json:"task_type"`
	Attempts       int64   `json:"attempts"`
	Successes      int64   `json:"successes"`
	TotalCost      float64 `json:"total_cost"`
	AvgTokens      int64   `json:"avg_tokens"`
	AvgTimeSeconds int64   `json:"avg_time_seconds"`
	UpdatedAt      string  `json:"updated_at"`
}

type Prompt struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	Complexity  sql.NullString `json:"complexity"`
	Template    string         `json:"template"`
	Variables   sql.NullString `json:"variables"`
	Source      string         `json:"source"`
	CreatedAt   string         `json:"created_at"`
}

type Session struct {
	ID               string         `json:"id"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	Project          string         `json:"project"`
	Prompt           sql.NullString `json:"prompt"`
	Status           string         `json:"status"`
	StartedAt        string         `json:"started_at"`
	EndedAt          sql.NullString `json:"ended_at"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	CacheReadTokens  int64          `json:"cache_read_tokens"`
	CacheWriteTokens int64          `json:"cache_write_tokens"`
	Cost             float64        `json:"cost"`
	Summary          sql.NullString `json:"summary"`
	Tags             sql.NullString `json:"tags"`
	RawPath          sql.NullString `json:"raw_path"`
	CreatedAt        string         `json:"created_at"`
}

type SessionsFt struct {
	Prompt  string `json:"prompt"`
	Summary string `json:"summary"`
	Tags    string `json:"tags"`
}
