// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const countMistakesByType = `-- name: CountMistakesByType :one
SELECT COUNT(*) FROM mistakes WHERE type = ?
`

func (q *Queries) CountMistakesByType(ctx context.Context, type_ string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countMistakesByType, type_)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFileChange = `-- name: CreateFileChange :execresult
INSERT INTO file_changes (id, session_id, file_path, additions, deletions, classification, accepted)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateFileChangeParams struct {
	ID             string         `json:"id"`
	SessionID      string         `json:"session_id"`
	FilePath       string         `json:"file_path"`
	Additions      sql.NullInt64  `json:"additions"`
	Deletions      sql.NullInt64  `json:"deletions"`
	Classification sql.NullString `json:"classification"`
	Accepted       sql.NullInt64  `json:"accepted"`
}

func (q *Queries) CreateFileChange(ctx context.Context, arg CreateFileChangeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createFileChange,
		arg.ID,
		arg.SessionID,
		arg.FilePath,
		arg.Additions,
		arg.Deletions,
		arg.Classification,
		arg.Accepted,
	)
}

const createMistake = `-- name: CreateMistake :execresult
INSERT INTO mistakes (id, session_id, type, description, context, correction, file_path)
VALUES (?, ?, ?, ?, ?, ?, ?)
`

type CreateMistakeParams struct {
	ID          string         `json:"id"`
	SessionID   string         `json:"session_id"`
	Type        string         `json:"type"`
	Description string         `json:"description"`
	Context     sql.NullString `json:"context"`
	Correction  sql.NullString `json:"correction"`
	FilePath    sql.NullString `json:"file_path"`
}

func (q *Queries) CreateMistake(ctx context.Context, arg CreateMistakeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createMistake,
		arg.ID,
		arg.SessionID,
		arg.Type,
		arg.Description,
		arg.Context,
		arg.Correction,
		arg.FilePath,
	)
}

const createPrompt = `-- name: CreatePrompt :execresult
INSERT INTO prompts (id, name, description, tags, complexity, template, variables, source)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreatePromptParams struct {
	ID          string         `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	Complexity  sql.NullString `json:"complexity"`
	Template    string         `json:"template"`
	Variables   sql.NullString `json:"variables"`
	Source      string         `json:"source"`
}

func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrompt,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Tags,
		arg.Complexity,
		arg.Template,
		arg.Variables,
		arg.Source,
	)
}

const deletePrompt = `-- name: DeletePrompt :exec
DELETE FROM prompts WHERE name = ?
`

func (q *Queries) DeletePrompt(ctx context.Context, name string) error {
	_, err := q.db.ExecContext(ctx, deletePrompt, name)
	return err
}

const getModelPerformance = `-- name: GetModelPerformance :many
SELECT id, model, task_type, attempts, successes, total_cost, avg_tokens, avg_time_seconds, updated_at FROM model_performance
WHERE model = ?
ORDER BY task_type ASC
`

func (q *Queries) GetModelPerformance(ctx context.Context, model string) ([]ModelPerformance, error) {
	rows, err := q.db.QueryContext(ctx, getModelPerformance, model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPerformance{}
	for rows.Next() {
		var i ModelPerformance
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.TaskType,
			&i.Attempts,
			&i.Successes,
			&i.TotalCost,
			&i.AvgTokens,
			&i.AvgTimeSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPrompt = `-- name: GetPrompt :one
SELECT id, name, description, tags, complexity, template, variables, source, created_at FROM prompts WHERE name = ?
`

func (q *Queries) GetPrompt(ctx context.Context, name string) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPrompt, name)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Tags,
		&i.Complexity,
		&i.Template,
		&i.Variables,
		&i.Source,
		&i.CreatedAt,
	)
	return i, err
}

const listFileChanges = `-- name: ListFileChanges :many
SELECT id, session_id, file_path, additions, deletions, classification, accepted, created_at FROM file_changes WHERE session_id = ? ORDER BY file_path ASC
`

func (q *Queries) ListFileChanges(ctx context.Context, sessionID string) ([]FileChange, error) {
	rows, err := q.db.QueryContext(ctx, listFileChanges, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FileChange{}
	for rows.Next() {
		var i FileChange
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FilePath,
			&i.Additions,
			&i.Deletions,
			&i.Classification,
			&i.Accepted,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMistakes = `-- name: ListMistakes :many
SELECT id, session_id, type, description, context, correction, file_path, created_at FROM mistakes
WHERE session_id = ?
ORDER BY created_at DESC
`

func (q *Queries) ListMistakes(ctx context.Context, sessionID string) ([]Mistake, error) {
	rows, err := q.db.QueryContext(ctx, listMistakes, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mistake{}
	for rows.Next() {
		var i Mistake
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Description,
			&i.Context,
			&i.Correction,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMistakesByType = `-- name: ListMistakesByType :many
SELECT id, session_id, type, description, context, correction, file_path, created_at FROM mistakes
WHERE type = ?
ORDER BY created_at DESC
LIMIT ?
`

type ListMistakesByTypeParams struct {
	Type  string `json:"type"`
	Limit int64  `json:"limit"`
}

func (q *Queries) ListMistakesByType(ctx context.Context, arg ListMistakesByTypeParams) ([]Mistake, error) {
	rows, err := q.db.QueryContext(ctx, listMistakesByType, arg.Type, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Mistake{}
	for rows.Next() {
		var i Mistake
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Type,
			&i.Description,
			&i.Context,
			&i.Correction,
			&i.FilePath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listModelPerformance = `-- name: ListModelPerformance :many
SELECT id, model, task_type, attempts, successes, total_cost, avg_tokens, avg_time_seconds, updated_at FROM model_performance
ORDER BY successes DESC
`

func (q *Queries) ListModelPerformance(ctx context.Context) ([]ModelPerformance, error) {
	rows, err := q.db.QueryContext(ctx, listModelPerformance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ModelPerformance{}
	for rows.Next() {
		var i ModelPerformance
		if err := rows.Scan(
			&i.ID,
			&i.Model,
			&i.TaskType,
			&i.Attempts,
			&i.Successes,
			&i.TotalCost,
			&i.AvgTokens,
			&i.AvgTimeSeconds,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPrompts = `-- name: ListPrompts :many
SELECT id, name, description, tags, complexity, template, variables, source, created_at FROM prompts ORDER BY name ASC
`

func (q *Queries) ListPrompts(ctx context.Context) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPrompts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.Complexity,
			&i.Template,
			&i.Variables,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptsBySource = `-- name: ListPromptsBySource :many
SELECT id, name, description, tags, complexity, template, variables, source, created_at FROM prompts WHERE source = ? ORDER BY name ASC
`

func (q *Queries) ListPromptsBySource(ctx context.Context, source string) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPromptsBySource, source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Tags,
			&i.Complexity,
			&i.Template,
			&i.Variables,
			&i.Source,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrompt = `-- name: UpdatePrompt :exec
UPDATE prompts SET description = ?, tags = ?, complexity = ?, template = ?, variables = ?
WHERE name = ?
`

type UpdatePromptParams struct {
	Description sql.NullString `json:"description"`
	Tags        sql.NullString `json:"tags"`
	Complexity  sql.NullString `json:"complexity"`
	Template    string         `json:"template"`
	Variables   sql.NullString `json:"variables"`
	Name        string         `json:"name"`
}

func (q *Queries) UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error {
	_, err := q.db.ExecContext(ctx, updatePrompt,
		arg.Description,
		arg.Tags,
		arg.Complexity,
		arg.Template,
		arg.Variables,
		arg.Name,
	)
	return err
}

const upsertModelPerformance = `-- name: UpsertModelPerformance :exec
INSERT INTO model_performance (id, model, task_type, attempts, successes, total_cost, avg_tokens, avg_time_seconds)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(model, task_type) DO UPDATE SET
    attempts = excluded.attempts,
    successes = excluded.successes,
    total_cost = excluded.total_cost,
    avg_tokens = excluded.avg_tokens,
    avg_time_seconds = excluded.avg_time_seconds,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ','now')
`

type UpsertModelPerformanceParams struct {
	ID             string  `json:"id"`
	Model          string  `json:"model"`
	TaskType       string  `json:"task_type"`
	Attempts       int64   `json:"attempts"`
	Successes      int64   `json:"successes"`
	TotalCost      float64 `json:"total_cost"`
	AvgTokens      int64   `json:"avg_tokens"`
	AvgTimeSeconds int64   `json:"avg_time_seconds"`
}

func (q *Queries) UpsertModelPerformance(ctx context.Context, arg UpsertModelPerformanceParams) error {
	_, err := q.db.ExecContext(ctx, upsertModelPerformance,
		arg.ID,
		arg.Model,
		arg.TaskType,
		arg.Attempts,
		arg.Successes,
		arg.TotalCost,
		arg.AvgTokens,
		arg.AvgTimeSeconds,
	)
	return err
}
