// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountMessagesBySession(ctx context.Context, sessionID string) (int64, error)
	CountMistakesByType(ctx context.Context, type_ string) (int64, error)
	CountSessions(ctx context.Context, project string) (int64, error)
	CreateCostRecord(ctx context.Context, arg CreateCostRecordParams) (sql.Result, error)
	CreateFileChange(ctx context.Context, arg CreateFileChangeParams) (sql.Result, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (sql.Result, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (sql.Result, error)
	CreateMistake(ctx context.Context, arg CreateMistakeParams) (sql.Result, error)
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error)
	DeleteMemory(ctx context.Context, id string) error
	DeleteMessagesBySession(ctx context.Context, sessionID string) error
	DeletePrompt(ctx context.Context, name string) error
	DeleteSession(ctx context.Context, id string) error
	GetBudget(ctx context.Context, project string) (Budget, error)
	GetCostByProject(ctx context.Context, project string) (GetCostByProjectRow, error)
	GetCostByProjectMonth(ctx context.Context, project string) (GetCostByProjectMonthRow, error)
	GetCostByProjectToday(ctx context.Context, project string) (GetCostByProjectTodayRow, error)
	GetCostByProjectWeek(ctx context.Context, project string) (GetCostByProjectWeekRow, error)
	GetCostBySession(ctx context.Context, sessionID string) (GetCostBySessionRow, error)
	GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error)
	GetMessage(ctx context.Context, id int64) (Message, error)
	GetMessagesBySession(ctx context.Context, sessionID string) ([]Message, error)
	GetModelPerformance(ctx context.Context, model string) ([]ModelPerformance, error)
	GetPrompt(ctx context.Context, name string) (Prompt, error)
	GetSession(ctx context.Context, id string) (Session, error)
	ListCostRecords(ctx context.Context, arg ListCostRecordsParams) ([]CostRecord, error)
	ListCostRecordsByDate(ctx context.Context, project string) ([]ListCostRecordsByDateRow, error)
	ListFileChanges(ctx context.Context, sessionID string) ([]FileChange, error)
	ListMemories(ctx context.Context, project string) ([]Memory, error)
	ListMemoriesByType(ctx context.Context, arg ListMemoriesByTypeParams) ([]Memory, error)
	ListMistakes(ctx context.Context, sessionID string) ([]Mistake, error)
	ListMistakesByType(ctx context.Context, arg ListMistakesByTypeParams) ([]Mistake, error)
	ListModelPerformance(ctx context.Context) ([]ModelPerformance, error)
	ListPrompts(ctx context.Context) ([]Prompt, error)
	ListPromptsBySource(ctx context.Context, source string) ([]Prompt, error)
	ListRecentSessions(ctx context.Context, limit int64) ([]Session, error)
	ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error)
	ListSessionsByStatus(ctx context.Context, arg ListSessionsByStatusParams) ([]Session, error)
	SearchMemories(ctx context.Context, arg SearchMemoriesParams) ([]Memory, error)
	SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]Session, error)
	UpdateMemory(ctx context.Context, arg UpdateMemoryParams) error
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error
	UpdateSessionCost(ctx context.Context, arg UpdateSessionCostParams) error
	UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error
	UpdateSessionSummary(ctx context.Context, arg UpdateSessionSummaryParams) error
	UpsertBudget(ctx context.Context, arg UpsertBudgetParams) error
	UpsertMemory(ctx context.Context, arg UpsertMemoryParams) error
	UpsertModelPerformance(ctx context.Context, arg UpsertModelPerformanceParams) error
}

var _ Querier = (*Queries)(nil)
