// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package db

import (
	"context"
	"database/sql"
)

const countSessions = `-- name: CountSessions :one
SELECT COUNT(*) FROM sessions WHERE project = ?
`

func (q *Queries) CountSessions(ctx context.Context, project string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSessions, project)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSession = `-- name: CreateSession :execresult
INSERT INTO sessions (
    id, provider, model, project, prompt, status, input_tokens, output_tokens,
    cache_read_tokens, cache_write_tokens, cost, summary, tags, raw_path
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateSessionParams struct {
	ID               string         `json:"id"`
	Provider         string         `json:"provider"`
	Model            string         `json:"model"`
	Project          string         `json:"project"`
	Prompt           sql.NullString `json:"prompt"`
	Status           string         `json:"status"`
	InputTokens      int64          `json:"input_tokens"`
	OutputTokens     int64          `json:"output_tokens"`
	CacheReadTokens  int64          `json:"cache_read_tokens"`
	CacheWriteTokens int64          `json:"cache_write_tokens"`
	Cost             float64        `json:"cost"`
	Summary          sql.NullString `json:"summary"`
	Tags             sql.NullString `json:"tags"`
	RawPath          sql.NullString `json:"raw_path"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSession,
		arg.ID,
		arg.Provider,
		arg.Model,
		arg.Project,
		arg.Prompt,
		arg.Status,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.Cost,
		arg.Summary,
		arg.Tags,
		arg.RawPath,
	)
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE id = ?
`

func (q *Queries) DeleteSession(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, id)
	return err
}

const getSession = `-- name: GetSession :one
SELECT id, provider, model, project, prompt, status, started_at, ended_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost, summary, tags, raw_path, created_at FROM sessions WHERE id = ?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.Model,
		&i.Project,
		&i.Prompt,
		&i.Status,
		&i.StartedAt,
		&i.EndedAt,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.Cost,
		&i.Summary,
		&i.Tags,
		&i.RawPath,
		&i.CreatedAt,
	)
	return i, err
}

const listRecentSessions = `-- name: ListRecentSessions :many
SELECT id, provider, model, project, prompt, status, started_at, ended_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost, summary, tags, raw_path, created_at FROM sessions
ORDER BY started_at DESC
LIMIT ?
`

func (q *Queries) ListRecentSessions(ctx context.Context, limit int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listRecentSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Project,
			&i.Prompt,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.Cost,
			&i.Summary,
			&i.Tags,
			&i.RawPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT id, provider, model, project, prompt, status, started_at, ended_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost, summary, tags, raw_path, created_at FROM sessions
WHERE project = ?
ORDER BY started_at DESC
LIMIT ? OFFSET ?
`

type ListSessionsParams struct {
	Project string `json:"project"`
	Limit   int64  `json:"limit"`
	Offset  int64  `json:"offset"`
}

func (q *Queries) ListSessions(ctx context.Context, arg ListSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions, arg.Project, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Project,
			&i.Prompt,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.Cost,
			&i.Summary,
			&i.Tags,
			&i.RawPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsByStatus = `-- name: ListSessionsByStatus :many
SELECT id, provider, model, project, prompt, status, started_at, ended_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost, summary, tags, raw_path, created_at FROM sessions
WHERE project = ? AND status = ?
ORDER BY started_at DESC
`

type ListSessionsByStatusParams struct {
	Project string `json:"project"`
	Status  string `json:"status"`
}

func (q *Queries) ListSessionsByStatus(ctx context.Context, arg ListSessionsByStatusParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsByStatus, arg.Project, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Project,
			&i.Prompt,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.Cost,
			&i.Summary,
			&i.Tags,
			&i.RawPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSessions = `-- name: SearchSessions :many
SELECT id, provider, model, project, prompt, status, started_at, ended_at, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, cost, summary, tags, raw_path, created_at FROM sessions
WHERE prompt LIKE '%' || ? || '%' OR summary LIKE '%' || ? || '%'
LIMIT ?
`

type SearchSessionsParams struct {
	Column1 sql.NullString `json:"column_1"`
	Column2 sql.NullString `json:"column_2"`
	Limit   int64          `json:"limit"`
}

func (q *Queries) SearchSessions(ctx context.Context, arg SearchSessionsParams) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, searchSessions, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Session{}
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Project,
			&i.Prompt,
			&i.Status,
			&i.StartedAt,
			&i.EndedAt,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.Cost,
			&i.Summary,
			&i.Tags,
			&i.RawPath,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSessionCost = `-- name: UpdateSessionCost :exec
UPDATE sessions SET
    input_tokens = ?, output_tokens = ?,
    cache_read_tokens = ?, cache_write_tokens = ?,
    cost = ?
WHERE id = ?
`

type UpdateSessionCostParams struct {
	InputTokens      int64   `json:"input_tokens"`
	OutputTokens     int64   `json:"output_tokens"`
	CacheReadTokens  int64   `json:"cache_read_tokens"`
	CacheWriteTokens int64   `json:"cache_write_tokens"`
	Cost             float64 `json:"cost"`
	ID               string  `json:"id"`
}

func (q *Queries) UpdateSessionCost(ctx context.Context, arg UpdateSessionCostParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionCost,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
		arg.Cost,
		arg.ID,
	)
	return err
}

const updateSessionStatus = `-- name: UpdateSessionStatus :exec
UPDATE sessions SET status = ?, ended_at = COALESCE(?, ended_at)
WHERE id = ?
`

type UpdateSessionStatusParams struct {
	Status  string         `json:"status"`
	EndedAt sql.NullString `json:"ended_at"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateSessionStatus(ctx context.Context, arg UpdateSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionStatus, arg.Status, arg.EndedAt, arg.ID)
	return err
}

const updateSessionSummary = `-- name: UpdateSessionSummary :exec
UPDATE sessions SET summary = ? WHERE id = ?
`

type UpdateSessionSummaryParams struct {
	Summary sql.NullString `json:"summary"`
	ID      string         `json:"id"`
}

func (q *Queries) UpdateSessionSummary(ctx context.Context, arg UpdateSessionSummaryParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionSummary, arg.Summary, arg.ID)
	return err
}
